site_name: StarSQL Wiki
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.path
    - content.code.copy
    - content.code.annotate
nav:
  - Home: 'index.md'
  - 'Initial Setup': 'initialsetup.md'
  - 'Basic Usage': 'basicusage.md'
  - 'Advanced Usage': 
      - Preamble: 'au-preamble.md'
      - ObjectCodecs: 'au-objectcodec.md'
      - TypeHandlers: 'au-typehandlers.md'
      - ForeignKeys: 'au-foreignkeys.md'
  - 'Misc Configuration': 'miscconfiguration.md'
repo_url: 'https://github.com/StarDevelopmentLLC/StarSQL'
repo_name: 'StarSQL'
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences